Tugas2PPW/urls.py
from django.contrib import admin
#import app_comment.urls as app_comment
import app_forum.urls as app_forum
import app_profil.urls as app_profil
import app_comment.urls as app_comment
import app_homepage.urls as app_homepage
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/app_homepage/", permanent="true"), name='app_homepage'),
    url(r'^app_comment/', include(app_comment, namespace='app_comment')),
    url(r'^app_homepage/', include(app_homepage,namespace='app_homepage')),
    url(r'^app_forum/', include(app_forum, namespace='app_forum')),
    url(r'^app_profil/', include(app_profil, namespace='app_profil')),

]

app_comment/urls.py
from django.conf.urls import url
from .views import index, status_post, add_comment
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^status_post', status_post, name='status_post'),
    url(r'^add_comment/(?P<pk>[0-9]+)/$', add_comment, name='add_comment'),
    #url(r'^result_post', message_table, name='result_post'),
]

app_comment/models.py
from django.db import models

# Create your models here.
class Update(models.Model):
    message = models.CharField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)
# class Reply(models.Model):
#     message = models.CharField(max_length=140)
#     created_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
	comment = models.CharField(max_length=160)
	created_date = models.DateTimeField(auto_now_add=True)
	status = models.ForeignKey(Update, null=True, blank=True)

app_comment/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Ceritanya Dummy Post Maker'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 1,
        'class': 'todo-form-textarea',
        'placeholder':' Komentar Anda ...'
    }

    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

app_comment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime, date
from .models import Update, Comment
from django.http import HttpResponseRedirect
from .forms import Message_Form, Comment_Form
from django.views.decorators.csrf import csrf_exempt

response = {'author': "Misael Jonathan"}
curr_year = int(datetime.now().strftime("%Y"))
timeline_status = {}
def index(request):
    response = {}
    response['message_form'] = Message_Form
    message = Update.objects.all()
    response['message'] = message
    comment = Comment.objects.all()
    response['comment'] = comment
    response['todo_form'] = Message_Form
    response['comment_form'] = Comment_Form
    return render(request, 'app_comment.html', response)

def status_post(request):
    form = Message_Form(request.POST or None)
    response['message_form'] = Message_Form
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        message = Update(message=response['status'])
        message.save()
        return HttpResponseRedirect('/app_comment/')
    else:
        return HttpResponseRedirect('/app_comment/')

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

def add_comment(request, pk):
	status = Update.objects.get(pk=pk)
	form = Comment_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['comment'] = request.POST['comment']
		comment=Comment(comment=response['comment'])
		comment.status = status
		comment.save()
		return redirect('/app_comment/')
	else:
		return HttpResponseRedirect('/app_comment/')

app_comment/templates/app_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="\static\css\app_comment.css"/>
</head>
<body>
  {% include "header.html" %}
  <!-- <h1> tes hehe</h1> -->
  <div class = "container-judul">
    <!-- <h1 id="title" class="main-title">Update Status</h1> -->
  </div>
  <div class = "big-container">
  <section name="input-list" id="input-list">
    <div class="container">
        <form id="form_isi" method="POST" action="{% url 'app_comment:status_post' %}">
            {% csrf_token %}
            {{ message_form }}
            <button class="btn">Post</button>
            <div class="modal">
              <div class="modal__box">
                <p> Apakah anda yakin ingin melakukan post ? </p>
                <p style="font-size: 10px"> Click post untuk melanjutkan </p>
                <p style="font-size: 10px"> Click sekitar untuk membatalkan </p>


                <input id="submit" type="submit" class="btn btn-sm btn-info" value="Submit">
              </div>
            </div>
            <br>
            </form>
            </div>
            </section>
            <section name="timeline" class="timeline" id="timeline">
            <div class="container">
            <div class="flex">
                {% for data in message %}
                      <!-- DIBAWAH INI HARUSNYA KOLOM COMMENT HEHE  -->
                  <div class="flex-list-item-comment-section">
                    <div class="comment-section">
                        <div class="comment-section-comment">
                            {% if data.comment_set.all %}
                                {% for comment in data.comment_set.all %}
                                    <!-- <h4>{{profile.name}}</h4> -->
                                    <!-- <p>{{comment.comment}}</p> -->
                                    <div class ="flex-item" style=margin:auto">
                                      <h5>{{comment.comment}}</h5>
                                      <div class="to-do-list-date-added">{{comment.created_date}}></div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="comment-section-form">
                        <form id="form" method="POST" action="{% url 'app_comment:add_comment' pk=data.id%}" class="form-comment" style="color: black">
                            {% csrf_token %}
                            {{ comment_form }}
                            <input id="submit" type="submit" class="btn btn-sm btn-info" value="Submit" style="bottom: -10px">
                            <br>
                        </form>
                        </div>

                    </div>
                </div>
                <div class="flex-item">
                    <div class="to-do-list">
                      <div class="col-xs-2" style="padding-top:20px">
                        <img style="display: inline; border-radius: 50%; width: 110px; height: 110px; margin: auto; max-width: 500px;" class="photo" src="http://thumb.ibb.co/gb1pFb/unknown_profile.jpg" alt="unknown_profile" border="0"/>
                      </div>
                      <div class="col-xs-10" style="padding-top:20px">
                        <p class="to-do-list-name">Misael Jonathan</p>
                        <div class="to-do-list-description">
                            {{data.message}}
                        </div>
                        <div class="to-do-list-date-added">
                            {{data.created_date}}
                        </div>
                    </div>
                  </div>
                </div>
                  {% endfor %}
    </section>
  </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
    $(function() {
             $('a[href*="#"]:not([href="#"])').click(function() {
               if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                 var target = $(this.hash);
                 target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                 if (target.length) {
                   $('html, body').animate({
                     scrollTop: target.offset().top - 55
                   }, 1000);
                   return false;
                 }
               }
             });
           });
</body>
</html>

app_comment/templates/header.html
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
    <img src="http://thelinkmarketing.ie/wp-content/uploads/2016/10/logo-copy.png" alt="logo" height="40" width="100"/>
  </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="#home">Home</a></li>
                <li><a href="#features">Profile</a></li>
                <li><a href="#contact">Forum</a></li>
                <li class="login"><a href="#">Sign In</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>